### ISSUE TITLE
Hero banner carousel block

### ISSUE THREAD

**Issue by helms-charity** [aemsites/888de#10]
# This is a fader carousel with 3 manual navigation elements
Seen on the home page https://www.888.de/

![image](https://github.com/aemsites/888de/assets/3883795/428b063f-9c2c-4d2b-b897-6e85d54cef07)

## General slider notes

- option to upload up to 5 slides ("hero banner" )
- Note that these are video banner backgrounds
- ability for authors to set the transition duration
- each slide has correlation to the relevant box offer below it, and the dot navigation.
- The left and right arrows act as manual "previous" and "next" buttons
- dots act as manual navigation and are different colors
- The areas under the dot nav also act as manual slide navigation, but the CTA within is an external link.
- Any links that are authored need to have authorable attributes - see https://github.com/aemsites/888de/issues/29

## "hero banner" specific notes

- option to upload a background image
- option to upload the barnd logo image 888sport/888slots/888poker
- offer is editable via rich text component (Charity has scope questions how rich this text needs to be)
- CTA layout and design is fixed, once hovering the BG and text colors are changing
- CTA can have the option for a link (URL) or javascript (Charity has security and functional questions on this JS requirement)
- CTA should have an option to GA event (see https://github.com/aemsites/888de/issues/29)
- T&C  should be a link (URL), once hovering the text color is changing
- T&C is optional
- T&C should have an option to GA event
- should have an option to add disclamer (richtext) on the image (we will need font size/style specs for that)

## Slide "preview" area below dot nav

- offer is editable via rich text component
- CTA layout and design is fixes, once hovering the BG and text colors are chaning (based on brand color)
- CTA can have the option for a link (URL) or javascript
- CTA shoild have an option to GA event
- welcome bonus should be a link (URL), once hovering the text color is changing
- welcome bonus text is optional
- welcome bonus  should have an option to GA event

**Comment by rafim888** [comment]
![image](https://github.com/aemsites/888de/assets/158305415/3b3ae56a-34e7-4fb0-8e7d-700f3ef6af1d)
