### ISSUE TITLE
Inner page template

### ISSUE THREAD

**Issue by helms-charity** [aemsites/888de#12]
# there are 3 left nav styles
There seem to be 4 sets of left navigation, we can either consider an embedded Fragment, or we can auto-block based on child pages?

## Left nav
- it is sticky to the nav (doesn't scroll with page)

### option 1
- anchors, hovered (colored) once scrolling the page 
- https://www.888.de/uber-uns/

### option 2
- straightforward, linking to other pages colored when showing the current page.

Q: Is the intent that the page you are on will have the left navigation link selected?
A: "the menu item is not changing and stays on Einzahlungen/Auszahlungen is because you navigating inside the section".
These separate pages all have the same item highlighted:
https://www.888.de/banking/einzahlung/wie-einzahlen/
https://www.888.de/banking/einzahlung/zahlungsmethode/
https://www.888.de/banking/einzahlung/einzahlungslimits/
https://www.888.de/banking/einzahlung/zeitrahmen/

These also should behave the same way:
https://www.888.de/banking/abhebung/richtlinie/
https://www.888.de/banking/abhebung/wie-abheben/
https://www.888.de/banking/abhebung/zeitrahmen/

This set of pages has the same left nav items, and the highlighted item DOES change:
https://www.888.de/sicherheit-datenschutz/betruegerische-emails/ 
https://www.888.de/sicherheit-datenschutz/cookie-unternehmenspolitik/ 
https://www.888.de/sicherheit-datenschutz/datenschutzrichtlinie/
https://www.888.de/sicherheit-datenschutz/faires-spiel/
https://www.888.de/sicherheit-datenschutz/keine-spyware/
https://www.888.de/sicherheit-datenschutz/lizensierung/
https://www.888.de/sicherheit-datenschutz/nutzungsvereinbarung/
https://www.888.de/sicherheit-datenschutz/quelle-der-geldmittel/
https://www.888.de/sicherheit-datenschutz/sichere-transaktionen/
https://www.888.de/sicherheit-datenschutz/
https://www.888.de/sicherheit-datenschutz/verantwortungsbewusstes-spielen/
https://www.888.de/sicherheit-datenschutz/verbindungsunterbrechungen/

This page seems to be the only 1 that has only 1 left nav item, is that intended?
https://www.888.de/bonusregelungen/ 

### option 3 - NO left nav
https://www.888.de/aktionen/
https://www.888.de/banking/ 

## breadcrumbs
See #7 

## Title + content
-` <h1> - <h6>` available tags, with respective font size
- freeform text

## FAQ pages use "inner" template, but have no breadcrumbs or left nav.

The 4 888club pages do have a top subnav:
https://www.888.de/888club/faq/
https://www.888.de/888club/vorteile/

These FAQ pages do not:
https://www.888.de/faq-poker-de/
https://www.888.de/faq-slots-de/

https://www.888.de/888club-tnc/ - confirmed should not have breadcrumbs.

**Comment by rafim888** [comment]
**Option 1**- is internal navigation and should stay this way
**option 2** -  banking pages have 2 section >> How to Deposit (Einzahlungen) and How tp withdraw (Auszahlungen)
each sectio has pages under it , the menu item is not changing and stays on Einzahlungen/Auszahlungen is because you navigating inside the section

https://www.888.de/sicherheit-datenschutz/ - should remain as today
**option 3 -** 

- https://www.888.de/aktionen/
- https://www.888.de/banking/

should have no navigation (as today)
