### ISSUE TITLE
Cookie banner is not translated

### ISSUE THREAD

**Issue by jeric888williamhill** [aemsites/888de#161]
Hi @helms-charity,

Please see bug details below:

**Pre requisite:**
Clear cookies and cache

**Steps to Reproduce:**
1. Access https://eds-www.888.de/
2. At the lower right bottom of the page, notice that the Cookie banner is not translated.

<img width="959" alt="cookie banner" src="https://github.com/aemsites/888de/assets/165638341/f686b890-65bc-4e8b-8efd-2d70ab07ea92">

**Comment by helms-charity** [comment]
@rafim888 is this controlled from the 888 side?

**Comment by jeric888williamhill** [comment]
Fixed/verified for this issue. Closing now.
