### ISSUE TITLE
Homepage: Incorrect redirection of Jetzt Anmelden CTA

### ISSUE THREAD

**Issue by jeric888williamhill** [aemsites/888de#164]
Hi @helms-charity,

Please see bug details below:

Steps to Reproduce:
1. Access https://eds-www.888.de/
2. Click any of the CTA in the highlighted image below.
3. Notice that it redirects to www.888.de

<img width="959" alt="CTA" src="https://github.com/aemsites/888de/assets/165638341/7aea36c5-29c3-44a1-b6d0-9e751dab6bca">

Expected Result:
It should redirect to the registration form of relevant site.

**Comment by kailasnadh790** [comment]
@jeric888williamhill issue is fixed...Please review.

**Comment by jeric888williamhill** [comment]
Hi @kailasnadh790,

This issue has been fixed verified.
Closing this issue.

Thanks!
