### ISSUE TITLE
Inner pages: Missing content in the breadcrumbs of left navigation menu

### ISSUE THREAD

**Issue by jeric888williamhill** [aemsites/888de#165]
Hi @helms-charity,

Please see bug details below:

Steps to Reproduce:
1. Access https://eds-www.888.de/banking/einzahlung/wie-einzahlen/
2. Notice that there is a missing word in the breadcrumbs. It should have the word "Banking" as compared with original site.

<img width="950" alt="breadcrumbs" src="https://github.com/aemsites/888de/assets/165638341/dc112386-0c8b-4dd5-a81e-d864e8a38741">

Note: Applies to all tabs of the left navigation menu.

**Comment by dave-fink** [comment]
@jeric888williamhill If this is fixed please go ahead and close this issue. If it's still valid please let me know.

**Comment by jeric888williamhill** [comment]
Hi @dave-fink ,

This issue has been fixed verified.
Closing this issue.

Thanks!
