### ISSUE TITLE
Inner pages: Missing word in the page

### ISSUE THREAD

**Issue by jeric888williamhill** [aemsites/888de#166]
Hi @helms-charity,

Please see bug details below:

**Steps to Reproduce:**
1. Access https://eds-www.888.de/banking/einzahlung/zahlungsmethode/
2. For the bulleted points, notice that there is a missing word. It should have the word "Aktzeptierte" before "Zahlungsmethode" as compared with the original site.

<img width="958" alt="missing" src="https://github.com/aemsites/888de/assets/165638341/fc1e0617-d511-43b4-b80a-3e83a8dd1e3b">

**Comment by dave-fink** [comment]
@jeric888williamhill This issue has been resolved. Please check it and if it's good close out the ticket.

**Comment by jeric888williamhill** [comment]
> @jeric888williamhill This issue has been resolved. Please check it and if it's good close out the ticket.

Hi @dave-fink ,

I just noticed that letter "n" is missing in the word "Zahlungsmethoden".

**Comment by dave-fink** [comment]
The links have been updated.  This is part of content and can be edited easily.

**Comment by jeric888williamhill** [comment]
Thanks. Closing this issue.
