### ISSUE TITLE
FAQ page template

### ISSUE THREAD

**Issue by helms-charity** [aemsites/888de#17]
# Similar to inner page, but no breadcrumbs or left nav.
This does not actually need to be a "template", since it is on a simple white background.

Might have a set of links under the header:
https://www.888.de/888club/faq/
https://www.888.de/888club/vorteile/

Or it may not:
https://www.888.de/faq-poker-de/
https://www.888.de/faq-slots-de/

https://www.888.de/888club-tnc/ - confirmed should not have breadcrumbs.

**Comment by rafim888** [comment]
hi @helms-charity 
we can have on template called "inner-page", and create  an acordion component for the FAQ.
this component  will be used cross site

https://www.888.de/888club-tnc/ - **no** need for breadcrumbs

**Comment by helms-charity** [comment]
Closing, as I have added this information to https://github.com/aemsites/888de/issues/12 .
