### ISSUE TITLE
Table block with fixed height

### ISSUE THREAD

**Issue by helms-charity** [aemsites/888de#18]
https://www.888.de/888club/Level-Struktur/

This page has the "club" link banner under the header, but the background of the page is black and has the table on it. It is the only one like it.

Notice the large scroll within a limited space, which creates a weird void when the window is taller. Is this intentional?
![image](https://github.com/aemsites/888de/assets/3883795/484027d3-0167-4a63-9d39-2294e9ab5f04)

**Comment by rafim888** [comment]
https://www.888.de/888club has several page under it, the navigation is done by "tabs"
![image](https://github.com/aemsites/888de/assets/158305415/ec867f71-a19e-4ade-8f68-e5b33f60adca)
where the current page is highlighted
