### ISSUE TITLE
Footer: [Mobile - Android] The 888 logo does not fit in the rectangular box

### ISSUE THREAD

**Issue by jeric888williamhill** [aemsites/888de#184]
Hi @helms-charity,

Please check out bug details below:

Steps to reproduce:
1. Access https://eds-www.888.de/ using android device.
2. Navigate to the footer.
3. Notice that the 888+ logo does not fit in the rectangular box.

Note: Does not happen in PC and iOS devices. Android device used in this test is Samsung Galaxy S23 FE.

![image](https://github.com/aemsites/888de/assets/165638341/415308b7-b738-49fa-96ee-e62b32bb377f)

**Comment by helms-charity** [comment]
This can also be be seen using Chrome's iPhone SE emulator. 

The difference is that the size of the 18+ image is smaller to compensate for the width of the "verantwortungsbewusst" word.
![image](https://github.com/aemsites/888de/assets/3883795/fd59a7b0-b479-44ff-9249-f37cf94b52c5)

**Comment by dave-fink** [comment]
This has been fixed - please test.

**Comment by jeric888williamhill** [comment]
Hi @dave-fink,

Fixed verified.
Closing this issue.

Thanks!
