### ISSUE TITLE
[Mobile-Iphone] iPhone navigation bar overlaps with banner and hamburger menu

### ISSUE THREAD

**Issue by ByronA-888WHG** [aemsites/888de#189]
Hello @helms-charity,
Please look at the bug below
1. iPhone navigation bar overlaps with banner and hamburger menu
(Please see attached image)

Step to Replicate
1. Open eds-www.888.de in iPhone
2. Open hamburger menu
![image](https://github.com/aemsites/888de/assets/165295931/797e4d52-c74a-48df-95a7-490092a34278)
Thank you!

**Comment by helms-charity** [comment]
√ pass: iphone 12 mini, Safari and Chrome

**Comment by dave-fink** [comment]
@ByronA-888WHG Can you please know what version of the iPhone you are seeing this on?

**Comment by ByronA-888WHG** [comment]
Hi @dave-fink,
This was observed with iPhone 11
Thank you!

**Comment by helms-charity** [comment]
I am only seeing this with devices using iOS 15. 
@ByronA-888WHG are you able to tell what % of your current users are on iOS 15.x? It is end of life as of March 4, so I'm not sure this is a go-live blocking issue.
![image](https://github.com/aemsites/888de/assets/3883795/938c9435-bbc1-4237-90dc-68d960e99655)

**Comment by ByronA-888WHG** [comment]
Hi @helms-charity,
Apologies for the late reply. Regarding the % of user for this OS ver. let me reach out to @rafim888 about this and to clarify if this version should be supported. Currently he is on OOO, but we will get back to you once we got an answer from Rafi. Thank you!

**Comment by rafim888** [comment]
Hello @helms-charity , @ByronA-888WHG 
looking at Google Analytics for 888.de, i see most iPhone users have OS version 17 and up
![image](https://github.com/aemsites/888de/assets/158305415/2511866a-2a84-4f5b-9a36-086e25ce0985)
so i guess we are good here

**Comment by helms-charity** [comment]
Closed per Rafi's comment.
