### ISSUE TITLE
"Cookie Richtlinie" link leads to non EDS page

### ISSUE THREAD

**Issue by ByronA-888WHG** [aemsites/888de#193]
Hello @helms-charity,
Please look at the issue below

1. "Cookie Richtlinie" link leads to non EDS page
(Note: EDS page for the link exist)

Steps to replicate:
1. Click on "Cookie Richtlinie" from cookie banner
![2024-04-04_18-45-45](https://github.com/aemsites/888de/assets/165295931/6a9b6fd8-c7f6-4b03-a585-64b5c1d1c719)

Thanks!

**Comment by helms-charity** [comment]
This one I believe is expected, as when we go live that will be the link. @lwulffhart-888WH can confirm.

**Comment by rafim888** [comment]
@ByronA-888WHG this is ok,
once the EDS site will be moved to the currrnt domain (888.de), this page: https://www.888.de/sicherheit-datenschutz/cookie-unternehmenspolitik/ will be from EDS

**Comment by ByronA-888WHG** [comment]
Hello, @rafim888 and @helms-charity,
I appreciate it for clearing this for me. Closing this bug since this was not an issue.
Thank you!
