### ISSUE TITLE
"Einloggen" moves the page in the background when clicked

### ISSUE THREAD

**Issue by ByronA-888WHG** [aemsites/888de#194]
Hello @helms-charity,
Please look at the issue below
1. "Einloggen" moves the page in the background when clicked
(Note: This was observed for PC and Mobile, but not on tablets.)

Step to replicate
1. Click "Einloggen"
 

https://github.com/aemsites/888de/assets/165295931/5f677b32-a422-4872-81c2-c8938f276158

Thank you!

**Comment by helms-charity** [comment]
NOTE: This seems directly related to issue #195.
I only see this behavior in browser widths above about 1615px wide.

**Comment by ByronA-888WHG** [comment]
Hi @kailasnadh790 and @helms-charity,
Fix verified. Thank you for working on this!
![2024-04-05_18-05-17](https://github.com/aemsites/888de/assets/165295931/397a7840-95f1-4b1f-813b-e11a5582cbe2)
