### ISSUE TITLE
Carousel: Remove slider max-height for desktop widths

### ISSUE THREAD

**Issue by helms-charity** [aemsites/888de#195]
This seems to be the cause of issue #194 .

`slider.style.maxHeight = `${img.height}px`;` at carousel.js:122 is breaking the slider design in browser widths greater than around 1615px; my quick testing suggests you don't need to apply max-height above 600px wide.

**Comment by kailasnadh790** [comment]
@helms-charity I doubt this is the issue..as this shift is happening on all the pages (except 404) eg; https://main--888de--aemsites.hlx.page/banking. Looking into this further.

**Comment by helms-charity** [comment]
OK -- I have updated my comments in #194 since the login shift isn't isolated to the home page. But... The max-height is breaking the design still :-)
