### ISSUE TITLE
Revise 888-main.js "sCut"

### ISSUE THREAD

**Issue by helms-charity** [aemsites/888de#199]
Per the comment on https://github.com/aemsites/888de/pull/127

"We see that you added a new line:
let sCut;
causing an issue with the sCut code in the main.js file
the sCut object already exists in the site.
Once we remove that line it works fine.
Can you please remove this line and upload the change?"

**Comment by dave-fink** [comment]
This has been removed - please revalidate.

**Comment by rafim888** [comment]
@helms-charity , @dave-fink 
how can i move this ti QA ?
can't find them in the assignee list

**Comment by rafim888** [comment]
Talked to @ByronA-888WHG it works as expected, this can be closed

**Comment by jeric888williamhill** [comment]
Hi,
This issue has been fixed/verified.
Closing this issue. Thanks!
