### ISSUE TITLE
OneTrust cookie script/banner

### ISSUE THREAD

**Issue by helms-charity** [aemsites/888de#27]
how are we dealing with the cookielaw script...
![image](https://github.com/aemsites/888de/assets/3883795/6cc285b7-3a13-4462-b075-10ebe64f3a62)

https://cdn.cookielaw.org/scripttemplates/6.32.0/otBannerSdk.js
https://cdn.cookielaw.org/scripttemplates/otSDKStub.js

**Comment by rafim888** [comment]
Hello,
as mentioned on the meeting on Wednesday (28.02), the cookie message is injected from GTM container https://www.googletagmanager.com/gtm.js?id=GTM-NSNT2WJ
adding this script to all pages (hostname=eds-dev-www.888.de):
<html>
<body>


--
  | <script>(function(w,d,s,l,i){w[l]=w[l]\|\|[];w[l].push({'gtm.start':
  | new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  | j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.setAttribute('class','optanon-category-C0001');j.src=
  | 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  | })(window,document,'script','dataLayer','GTM-NSNT2WJ');</script>
  | 


</body>
</html>
should make it pop, as the trigger there 
![image](https://github.com/aemsites/888de/assets/158305415/37a5703d-5262-4556-bed1-70bc0dcd5a9f)

**Comment by rafim888** [comment]
@ #68

**Comment by dave-fink** [comment]
This is working now that GTM was added.
