### ISSUE TITLE
SEO requirments 

### ISSUE THREAD

**Issue by rafim888** [aemsites/888de#28]
- Links in the hamburger menu to stay the same
- Content on the page & throughout the page – to stay the same
- Images, logos, regulation images, payment method images – to stay the same
- Footer links - to stay the same (target URL + layout of 4 images)
- Cookie message - to stay the same
- Footer responsible gaming banner - to stay the same
- Links in CTA – to stay the same

**Comment by helms-charity** [comment]
SEO requirements are covered in #31
