### ISSUE TITLE
Home page LHS performance score

### ISSUE THREAD

**Issue by helms-charity** [aemsites/888de#57]
I could see some layout shift SOMETIMES (not all the time) when I set the network tab throttle to like slow 3G. 
Now that the header and carousel are both done, we can dig in.

**Comment by kailasnadh790** [comment]
Some improvements implemented. Could revisit later.

**Comment by kailasnadh790** [comment]
Address issue: https://cq-dev.slack.com/archives/C06G5A01NFM/p1709308339391019
