### ISSUE TITLE
SVG needed

### ISSUE THREAD

**Issue by kailasnadh790** [aemsites/888de#62]
Customer to provide svgs for the below:

page: https://www.888.de/888club/
- [ ] https://images.images4us.com/888_DE_V2/DE/logo-mobile-1634030257076_tcm2024-532884.png
- [ ] https://images.images4us.com/888_DE_V2/DE/logo-pc-1634030227763_tcm2024-532881.png

**Comment by rafim888** [comment]
Hi,
asked the rekevant teams in 888, 
also uploading an scg i converted with a free tool 
![70cbd26233709d28c5cd86843e588ec2](https://github.com/aemsites/888de/assets/158305415/c981d8a0-1c58-46ac-8c24-af190cb9c19b)

**Comment by kailasnadh790** [comment]
ya.. @rafim888 these free tools often don't do a great job.

**Comment by helms-charity** [comment]
I was able to find a generic Spade SVG to use, but I think for the logo we'll just use the original image on your site.

**Comment by helms-charity** [comment]
We ended up using the .png for the 888club image, and reusing the spade.svg for the green button per Rafi, so I will close this ticket.
