### ISSUE TITLE
 Legacy javascript files-888.de

### ISSUE THREAD

**Issue by rafim888** [aemsites/888de#69]
we have 3 javascript files loaded to the site:

1. https://umbrella-staticcontent.safe-iplay.com/umb/inner.js - deals with with accordion object of FAQ pages, **- not relevant as this functionality will be in EDS**
2. https://umbrella-staticcontent.safe-iplay.com/umb/hp.js - deals with with the main banner in the **home page, presenting the right offer.- not relevant as this functionality will be in EDS**
3. https://umbrella-staticcontent.safe-iplay.com/umb/main.js -deals with with opening the login/register popup,
![image](https://github.com/aemsites/888de/assets/158305415/0a207f78-b672-47a3-94ce-c31acf4fc3e3)
+ CTA finctions + GA/GTM events.
the l**ogin popus is not relevant any more, functionality will be in EDS**

the rest should be re- factored by 888 team, then intergtaed to the project, as external resource or part of the code base

**Comment by helms-charity** [comment]
What about these Google script tags, do we add them automatically for every page?

https://www.googleoptimize.com/optimize.js?id=OPT-NZNXP5B
https://www.googletagmanager.com/gtm.js?id=GTM-NSNT2WJ
https://www.google.com/ads/ga-audiences?t=sr&aip=1&_r=4&slf_rd=1&v=1&_v=j101&tid=UA-179688831-1&cid=41882173.1706468620&jid=1792696979&_u=QACAAEAAAAAAACAAI~&z=1414543889
https://www.google-analytics.com/analytics.js

**Comment by rafim888** [comment]
1 - should be added on each page, together with the datalayer
this way:
<html>
<body>


--
  | <script>(function(w,d,s,l,i){w[l]=w[l]\|\|[];w[l].push({'gtm.start':
  | new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  | j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.setAttribute('class','optanon-category-C0001');j.src=
  | 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  | })(window,document,'script','dataLayer','GTM-NSNT2WJ');</script>
  | 


</body>
</html>

2+3) can be dropped

**Comment by rafim888** [comment]
we will have the URL soon, what will be the best way to use it ?

**Comment by rafim888** [comment]
1) how do i publish the JSON ? from the share point ?
2) 10x, got it
4) we will have the URL soon, what will be the best way to use it ? - **ignore**, this is a different issue

**Comment by dave-fink** [comment]
@rafim888 I think this can be closed - can you confirm?  If there's anything left to do please let me know.

**Comment by yarivfel** [comment]
Before closing, I'm adding here the re-factored main.js file Rafi mentioned in the description of this [issue.]()
What is the process of integrate it to the project?
I assume it will be added to the repository?
[script.zip](https://github.com/aemsites/888de/files/14603188/script.zip)

**Comment by dave-fink** [comment]
Hello @yarivfel I reviewed this script, it looks like there's a few things going on in here (sCut, Smart Button - login, Google Analytics, DTM and a few other things) .  Can we set up some time to review this together?  The DOM for the Edge Delivery Service site is a bit different and therefore we'll likely need to rewrite some of this.   Please let me know if you have some time and we can jump on a call.  (I'll reach out on Slack as well)

**Comment by rafim888** [comment]
meeting set
