### ISSUE TITLE
More JS data elements?

### ISSUE THREAD

**Issue by helms-charity** [aemsites/888de#82]
How should we deal with these? Example is from https://www.888.de/faq-slots-de/ but it seems to be on all pages.

1. Is this what is populating the datalayer? Is this scripts element added dynamically via the Google scripts?

![image](https://github.com/aemsites/888de/assets/3883795/fd39afa7-43fd-4e17-86d0-5299364762c7)

2. I don't understand the purpose of thils:
`<script>var placeHoldersXML='&lt;Root&gt;&lt;ReplacementPair&gt;&lt;Key&gt;date&lt;/Key&gt;&lt;Value&gt;15.10.2020&lt;/Value&gt;&lt;/ReplacementPair&gt;&lt;ReplacementPair&gt;&lt;Key&gt;withdrawalDate&lt;/Key&gt;&lt;Value&gt;28.02.2021&lt;/Value&gt;&lt;/ReplacementPair&gt;&lt;ReplacementPair&gt;&lt;Key&gt;date1&lt;/Key&gt;&lt;Value&gt;15.10.2020&lt;/Value&gt;&lt;/ReplacementPair&gt;&lt;ReplacementPair&gt;&lt;Key&gt;date2&lt;/Key&gt;&lt;Value&gt;08.10.2020&lt;/Value&gt;&lt;/ReplacementPair&gt;&lt;ReplacementPair&gt;&lt;Key&gt;casinoDate&lt;/Key&gt;&lt;Value&gt;15.10.2020&lt;/Value&gt;&lt;/ReplacementPair&gt;&lt;ReplacementPair&gt;&lt;Key&gt;migrationDate&lt;/Key&gt;&lt;Value&gt;29.10.20&lt;/Value&gt;&lt;/ReplacementPair&gt;&lt;ReplacementPair&gt;&lt;Key&gt;pokerDate&lt;/Key&gt;&lt;Value&gt;02.11.2020&lt;/Value&gt;&lt;/ReplacementPair&gt;&lt;ReplacementPair&gt;&lt;Key&gt;campPause&lt;/Key&gt;&lt;Value&gt;08.10.2020&lt;/Value&gt;&lt;/ReplacementPair&gt;&lt;ReplacementPair&gt;&lt;Key&gt;wheelPause&lt;/Key&gt;&lt;Value&gt;15.10.2020&lt;/Value&gt;&lt;/ReplacementPair&gt;&lt;/Root&gt;';</script>`

**Comment by rafim888** [comment]
#1 - this populated from our current platform (Tridion), on every page
        i guess that we will have an option to add it using the integration to 888 platform
        for example: var country = "{{country,}}";
#2 - you can ignore this

**Comment by dave-fink** [comment]
@rafim888 
I'm assuming this is like the other datalayer code we added.  Do you need us to put placeholder values in? If so do can you share what is needed?

**Comment by rafim888** [comment]
the datalayer is the same, in all pages
https://eds-www.888.de/uber-uns/
https://eds-www.888.de/faq-poker-de/

**Comment by helms-charity** [comment]
Datalayer code was merged via https://github.com/aemsites/888de/pull/178.
