### ISSUE TITLE
Library: Add table block variants

### ISSUE THREAD

**Issue by helms-charity** [aemsites/888de#87]
### This ticket has a dependency of #86 to be completed first.
Table block w/ variants need to be added to the library.

So far the 2 places we have tables are 

- https://main--888de--aemsites.hlx.page/888club/level-struktur
- https://main--888de--aemsites.hlx.page/sicherheit-datenschutz/cookie-unternehmenspolitik

Use the Accordion example for having multiple variants on the same Word doc:
https://main--888de--aemsites.hlx.page/tools/sidekick/library/blocks/accordion

**Comment by kailasnadh790** [comment]
library is updated with table block.
