### ISSUE TITLE
Proposed: open all external links in new tab

### ISSUE THREAD

**Issue by helms-charity** [aemsites/888de#88]
Question on site-wide linking attribute rules 

via https://adobe-dx-support.slack.com/archives/C05K6PERGKA/p1710161017983269 :
 - I would like to programmatically add `target="_blank"` to all external links, because I can see this seems to be a pattern.

- The feature of allowing authors to add more attributes will remain; I would make sure the attributes added in the Word document link text would append to any existing attributes that were put there programmatically.

**Comment by rafim888** [comment]
confirmed,
this is exactly the logic, each "external" link should be opened in a new tab/window
